### ISSUE TITLE
In the playlist commands file on line 39, 64, 92, and 119, shouldn't the ctx.Guild.Name be ctx.Guild.Id

### ISSUE THREAD

**Issue by alexjshepler** [karolNiedziela/DiscordBot#1]
[In here](https://github.com/alexjshepler/DiscordBot/blob/master/CustomBot/Commands/PlaylistCommands.cs#L64) would think that instead of saving the playlist to the server name you'd want to save it to the server-id because if two servers have the name, wouldn't they share the same playlists?

`var playlist = await _context.Playlists.SingleOrDefaultAsync(p => p.Name == playlistName && p.ServerName == ctx.Guild.Name);`

So it would be 
`var playlist = await _context.Playlists.SingleOrDefaultAsync(p => p.Name == playlistName && p.ServerID == ctx.Guild.ID);`
instead, and all you'd have to change would be in the Models the [Playlist.cs](https://github.com/alexjshepler/DiscordBot/blob/master/CustomBot.DAL/Models/Playlist.cs) the `public string ServerName { get; set; }` to ServerID

(I know that this isn't actively maintained, I was just wondering for me and others that are using this repository to build their own bots)

**Comment by karolNiedziela** [comment]
Thanks for advice!

I modified code as you mentioned. I added ServerId but also decided to keep ServerName too in [Playlist.cs](https://github.com/karolNiedziela/DiscordBot/blob/master/CustomBot.DAL/Models/Playlist.cs). 

In addition, i add few lines to provide information about empty playlist after skipping all tracks. You can check it in [MusicPlayer.cs](https://github.com/karolNiedziela/DiscordBot/blob/master/CustomBot/Modules/MusicPlayer.cs) class.
